language: r
sudo : false
cache: packages

r:
  - release

warnings_are_errors: false

before_deploy:
  - Rscript -e 'install.packages("devtools"); devtools::install(quick = TRUE); install.packages(c("pkgdown")); pkgdown::build_site();'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  local-dir: docs
  on:
    branch: master
