# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

before_deploy:
  - Rscript -e 'install.packages("devtools"); devtools::install(quick = TRUE); install.packages(c("pkgdown")); pkgdown::build_site();'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  local-dir: docs
  on:
    branch: master
