# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Source version of this workflow lives in https://github.com/slds-lmu/lecture_service
# Please only update by copying from there to avoid divergences
on:
  workflow_dispatch:
  push:
    branches: [main, master]

name: update-latex-math

jobs:
  update-latex-math:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Uncomment / move to get a tmux ssh session for interactive debugging
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      # PWD is same name as repo, e.g. "lecture_i2ml", confusing this contains the service repo and the lecture repo
      # is a child directory. Anwyway, basename ${PWD} is "lecture_XYZ" which is useful for us.
      - name: Get latex-math
        run: |
          curl -sL https://api.github.com/repos/slds-lmu/latex-math/tarball/master | tar -xz --directory=latex-math/ --strip-components=1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[Automated] Update latex-math"
          commit-message: "Update latex-math"
          branch: update-latex-math
          add-paths: latex-math
